//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.bill_details = new HashSet<bill_details>();
        }
    
        public int bill_id { get; set; }
        public int template_id { get; set; }
        public int patient_id { get; set; }
        public string bill_nr { get; set; }
        public int creator_id { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string description { get; set; }
        public string attachment_url { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
    
        public virtual user user { get; set; }
        public virtual patient patient { get; set; }
        public virtual template template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_details> bill_details { get; set; }
    }
}
