//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class casenote
    {
        public int casenote_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public int creator_id { get; set; }
        public int category_id { get; set; }
        public string attachment { get; set; }
        public string entry_text { get; set; }
        public Nullable<int> patient_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual user user { get; set; }
        public virtual patient patient { get; set; }
    }
}
