//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.bills = new HashSet<bill>();
            this.casenotes = new HashSet<casenote>();
            this.temp_search = new HashSet<temp_search>();
            this.temp_service = new HashSet<temp_service>();
        }
    
        public int patient_id { get; set; }
        public Nullable<int> patient_nr { get; set; }
        public string title { get; set; }
        public string salutation { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string other_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string marital_status { get; set; }
        public string email { get; set; }
        public string telefax { get; set; }
        public string street_address { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string affix { get; set; }
        public string zip { get; set; }
        public string town { get; set; }
        public Nullable<int> partner_id { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> isActive { get; set; }
        public string contact_person { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<casenote> casenotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temp_search> temp_search { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temp_service> temp_service { get; set; }
    }
}
