//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qm_sop
    {
        public int qm_sop_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string filePath { get; set; }
        public Nullable<int> qm_tree_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> approved_by { get; set; }
    
        public virtual department department { get; set; }
        public virtual user user { get; set; }
        public virtual qm_tree qm_tree { get; set; }
    }
}
