//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.bill_details = new HashSet<bill_details>();
            this.temp_service = new HashSet<temp_service>();
        }
    
        public int service_id { get; set; }
        public Nullable<int> creator_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> active { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public string type { get; set; }
        public Nullable<int> isFavourite { get; set; }
        public int service_catalog_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> category_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_details> bill_details { get; set; }
        public virtual category category { get; set; }
        public virtual service_catalog service_catalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temp_service> temp_service { get; set; }
    }
}
