//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_recording_details
    {
        public int user_id { get; set; }
        public int tc_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> duration { get; set; }
        public Nullable<long> duration2 { get; set; }
        public string comment { get; set; }
    
        public virtual time_recording time_recording { get; set; }
        public virtual user user { get; set; }
    }
}
