//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_detail
    {
        public int user_id { get; set; }
        public int department_id { get; set; }
        public Nullable<int> age { get; set; }
    
        public virtual department department { get; set; }
        public virtual user user { get; set; }
    }
}
