//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.bills = new HashSet<bill>();
            this.casenotes = new HashSet<casenote>();
            this.categories = new HashSet<category>();
            this.qm_sop = new HashSet<qm_sop>();
            this.temp_search = new HashSet<temp_search>();
            this.temp_service = new HashSet<temp_service>();
            this.templates = new HashSet<template>();
            this.time_recording = new HashSet<time_recording>();
            this.time_recording1 = new HashSet<time_recording>();
            this.time_recording_details = new HashSet<time_recording_details>();
            this.user_detail = new HashSet<user_detail>();
        }
    
        public int user_id { get; set; }
        public string emp_id { get; set; }
        public string salutation { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string other_name { get; set; }
        public string affix { get; set; }
        public string sex { get; set; }
        public string email { get; set; }
        public string doctor { get; set; }
        public string username { get; set; }
        public string acronym { get; set; }
        public string password { get; set; }
        public string confirm_password { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> isActive { get; set; }
        public string skin_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<casenote> casenotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category> categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qm_sop> qm_sop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temp_search> temp_search { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temp_service> temp_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<template> templates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<time_recording> time_recording { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<time_recording> time_recording1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<time_recording_details> time_recording_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_detail> user_detail { get; set; }
    }
}
